#!/usr/bin/env python3
"""Regenerate phishscope.py from the package sources.

    python tools/build_standalone.py

Run this after changing anything under phishscope/ so the committed
single-file build stays in sync. The result runs on Python >= 3.8 with
nothing but the standard library.
"""

from __future__ import annotations

import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SRC = ROOT / "phishscope"
OUT = ROOT / "phishscope.py"

HEADER = '''#!/usr/bin/env python3
"""PhishScope — offline, explainable phishing-URL risk engine.

Single-file build, generated by tools/build_standalone.py from the
phishscope/ package. Python >= 3.8, standard library only.

    python3 phishscope.py --explain paypa1.com
"""

from __future__ import annotations
'''

SECTIONS = ["data", "analyzer", "cli"]


def module_source(name: str) -> str:
    # Strip everything that only makes sense in a package context: the
    # docstring, the future import, intra-package imports, __all__.
    src = (SRC / f"{name}.py").read_text(encoding="utf-8")
    src = re.sub(r'\A("""|\'\'\').*?\1', "", src, count=1, flags=re.DOTALL)
    src = re.sub(r"^from __future__ import annotations\s*$", "", src, flags=re.MULTILINE)
    src = re.sub(r"^from \.[\w.]* import \([^)]*\)", "", src, flags=re.MULTILINE)
    src = re.sub(r"^from \.[\w.]* import .*$", "", src, flags=re.MULTILINE)
    src = re.sub(r"^__all__ = \[[^\]]*\]\s*$", "", src, flags=re.MULTILINE)
    src = re.sub(
        r'^if __name__ == "__main__":\n    raise SystemExit\(main\(\)\)\s*$',
        "",
        src,
        flags=re.MULTILINE,
    )
    return src.strip("\n")


def main() -> None:
    version = re.search(r'__version__ = "([^"]+)"', (SRC / "__init__.py").read_text(encoding="utf-8"))
    chunks = [HEADER]
    for name in SECTIONS:
        chunks.append(f"\n# --- from phishscope/{name}.py ---\n\n")
        chunks.append(module_source(name))
    chunks.append(
        f'\n\n__version__ = "{version.group(1)}"\n\n\n'
        'if __name__ == "__main__":\n    raise SystemExit(main())\n'
    )
    OUT.write_text("".join(chunks), encoding="utf-8")
    print(f"wrote {OUT} ({OUT.stat().st_size:,} bytes)")


if __name__ == "__main__":
    main()
